### PR TITLE
Pulse

### PR DESCRIPTION
**Pull request by leonmerker**

### CODE REVIEW

**Review by fuzhanrahmanian — COMMENTED** [review]
each process should have two scrips with the following names: 
i.e. process.py and process_plotting.py

As all the analyses that you will add are subdivision of pulse, then the names should be in the following:
pulse.py
pulse_GITT.py
pulse_PITT.py
pulse_plotting.py (for plotting you can also subdivide it.

**Review by fuzhanrahmanian — CHANGES_REQUESTED** [review]
- Sub directories should not be capitalized: "Pulse" -> pulse

- each process should have two scrips with the following names:
    i.e. process.py and process_plotting.py
    
   As all the analyses that you will add are subdivision of pulse, then the names should be in the following:
    pulse.py
    pulse_GITT.py
    pulse_PITT.py
    pulse_GITT_plotting.py .

**Comment by fuzhanrahmanian** [comment]
@leonmerker Hi Leon, if you no longer want to have the pulse in MADAP, shall I delete this pull ?

**Comment by leonmerker** [comment]
yeah can delete it

**Pull request closed without merging**
